#ifndef BMSTU_NET_CP_TPOOL_ERR_H
#define BMSTU_NET_CP_TPOOL_ERR_H

enum tpool_err_code{
    TPOOL_NO_ERR = 0,
    TPOOL_MEM_ALLOC_ERR = 1,
    TPOOL_THREAD_CREATE_ERR = 2
};

#endif //BMSTU_NET_CP_TPOOL_ERR_H
